name: attempt_merge_stable_to_main
on:
  workflow_call:
    inputs:
    secrets:
      envPAT:
        required: true

jobs:
  attempt_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.envPAT }}
          fetch-depth: 0
      - name: Attempt merge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git fetch
          git rebase --no-ff origin/stable
          git push
